config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :test_results
      resources :tools
      resources :benchmark_names
      resources :benchmark_spliteds
      resources :benchmark_types
      resources :days_to_runs
      resources :display_types

      root to: "test_results#index"
    end
  root to: 'pages#index'

  get '/show/:id', :to => 'pages#show', :as => 'show_tool'
  get '/benchmark_type/:id', :to => 'pages#show_type', :as => 'show_type'
  get '/log/:id', :to => 'pages#log', :as => 'log'
  get '/logerr/:id', :to => 'pages#logerr', :as => 'logerr'
  get '/show_diff/:id1/:id2/:level', :to => 'pages#show_diff', :as => 'show_diff'
end

app/views/partials/_header.html.slim
.ui.fixed.borderless.main.menu#mainMenu
  .left.menu
    .header.item
      h2
        |Trau Tester
    = link_to "Manual_Tester", "http://10.32.0.210/", class: "item large text"
    = link_to "Home", root_path, class: "item medium text"
    - @display_types.each do |display_type|
      = link_to "#{display_type.name}", show_type_path(display_type.id), class: "item medium text"



#diff-content
  form.ui.form
    .field
      label
        |Compare log
        .fields
          .seven.wide.field
            .two.fields
              .field
                .ui.radio.checkbox
                  input type="radio" name="r_difftype" value="0"
                  label sat/unsat 
              .field
                .ui.radio.checkbox
                  input type="radio" name="r_difftype" value="1"
                  label timeout
                .ui.radio.checkbox
                  input type="radio" name="r_difftype" value="2"
                  label all_diff
          .three.wide.field
            input type="text" name="r_id1" placeholder="Result id" id="r_id1"
          .three.wide.field
            input type="text" name="r_id2" placeholder="Result id" id="r_id2"
          .three.wide.field
            .ui.button onClick="compare_log();"
              |Submit

app/views/partials/_result_single.html.slim
table.ui.celled.unstackable.striped.table
  thead.color-lighter
    tr
      th
        |id
      th
        |date
      th
        |benchmak
      th
        |sat
      th
        |unsat
      th
        |unknown
      th
        |timeout
      th
        |exception/error
      th
        |misc
      th.right.aligned
        |commit
      th.right.aligned
        |logs
  tbody
    - if results != nil
      - results.each do |result|
        tr
          td.collapsing
              |#{result.id}
          td.collapsing
              |#{result.date}
          td.collapsing
              |#{result.benchmark}
          td.positive.collapsing
            |#{result.sat}
          td.error.collapsing
            |#{result.unsat}
          td.active.collapsing
            |#{result.unknown}
          td.warning.collapsing
            |#{result.timeout}
          td.active.collapsing
            |#{result.exception}
          td.active.collapsing
            |#{result.misc}
          td.collapsing.right.aligned
            - if tool_url != nil && result.commit != "-"
              a href="javascript:goto_commit('#{tool_url}','#{result.commit}');"
                |#{result.commit}
            - else
              |-

          td.collapsing.right.aligned
            = link_to log_path(result.id) do
              |log
            |,  
            = link_to logerr_path(result.id) do
              |log.full
            - if tool_name == "trauc"
              |, 
              a href="http://trauc.iis.sinica.edu.tw/z3-trace/#{tool_name}.#{result.date}.#{result.benchmark}/" target="_tab"
                |z3-trace

app/views/partials/_result_table.html.slim
table.ui.celled.unstackable.striped.table
  thead.color-lighter
    tr
      th
        |id
      th
        |Name
      th
        |date
      th
        |benchmark
      th
        |sat
      th
        |unsat
      th
        |unknown
      th
        |timeout
      th
        |exception/error
      th
        |misc
      th.right.aligned
        |commit
      th.right.aligned
        |logs
  tbody
    - if result_datas != nil 
      - result_datas.each do |result_data|
        tr
          td.collapsing
            - if not result_data.is_splited
                |#{result_data.test_result.id}
            - else
              a id="spliter_#{result_data.group_id}" onclick="open_splited(#{result_data.group_id});" style="cursor: pointer"
                i.angle.down.icon
          td.collapsing
            = link_to show_tool_path(result_data.tool.id) do
              |#{result_data.tool.name}
          td.collapsing
              |#{result_data.test_result.date}
          td.collapsing
              |#{result_data.test_result.benchmark}
          td.positive.collapsing
            |#{result_data.test_result.sat}
          td.error.collapsing
            |#{result_data.test_result.unsat}
          td.error.collapsing
            |#{result_data.test_result.unknown}
          td.warning.collapsing
            |#{result_data.test_result.timeout}
          td.warning.collapsing
            |#{result_data.test_result.exception}
          td.error.collapsing
            |#{result_data.test_result.misc}
          td.collapsing.right.aligned
            - if result_data.tool.repo_url != nil && result_data.test_result.commit != "-"
              a href="javascript:goto_commit('#{result_data.tool.repo_url}','#{result_data.test_result.commit}');"
                |#{result_data.test_result.commit}
            - else
              |-
          - if not result_data.is_splited
            td.collapsing.right.aligned
              = link_to log_path(result_data.test_result.id) do
                |log
              |,  
              = link_to logerr_path(result_data.test_result.id) do
                |log.full
              - if result_data.tool.name == "trauc"
                |, 
                a href="http://trauc.iis.sinica.edu.tw/z3-trace/#{result_data.tool.name}.#{result_data.test_result.date}.#{result_data.test_result.benchmark}/" target="_tab"
                  |z3-trace
          - else
            td.collapsing.right.aligned.disabled
              |log, log.full, z3-trace
        - if result_data.is_splited
          - result_data.children.each do |inner_data|
            tr class="splited_#{result_data.group_id}" style="display: none"
              td.collapsing
                |#{inner_data.test_result.id}
              td.collapsing.disabled
                |#{inner_data.tool.name}
              td.collapsing.disabled
                |#{inner_data.test_result.date}
              td.collapsing.disabled
                |#{inner_data.test_result.benchmark}
              td.collapsing
                |#{inner_data.test_result.sat}
              td.collapsing
                |#{inner_data.test_result.unsat}
              td.collapsing
                |#{inner_data.test_result.unknown}
              td.collapsing
                |#{inner_data.test_result.timeout}
              td.collapsing
                |#{inner_data.test_result.exception}
              td.collapsing
                |#{inner_data.test_result.misc}
              td.collapsing.right.aligned
                - if inner_data.tool.repo_url != nil && inner_data.test_result.commit != "-"
                  a href="javascript:goto_commit('#{inner_data.tool.repo_url}','#{inner_data.test_result.commit}');"
                    |#{inner_data.test_result.commit}
                - else
                  |-
              td.collapsing.right.aligned
                = link_to log_path(inner_data.test_result.id) do
                  |log
                |,  
                = link_to logerr_path(inner_data.test_result.id) do
                  |log.full
                - if inner_data.tool.name == "trauc"
                  |, 
                  a href="http://trauc.iis.sinica.edu.tw/z3-trace/#{inner_data.tool.name}.#{inner_data.test_result.date}.#{inner_data.test_result.benchmark}/" target="_tab"
                    |z3-trace